module.exports = {
  name: 'Poland',
  sites: [
    "https://www.facebook.com/ShellPolska/",
    "https://www.facebook.com/EtnoCafeKawiarnie",
    "https://www.facebook.com/mlekpol",
    "https://www.facebook.com/MLEKOVITA",
    "https://www.facebook.com/maxburgerspolska/",
    "https://www.facebook.com/czekolada",
    "https://www.facebook.com/PijalnieCzekolady",
    "https://www.facebook.com/sklepy.stokrotka",
    "https://www.facebook.com/kaufland.polska",
    "https://www.facebook.com/WawelSlodycze",
    "https://www.facebook.com/majonezkielecki",
    "https://www.facebook.com/saladstory",
    "https://www.facebook.com/tarczynskipl/",
    "https://www.facebook.com/grycan/",
    "https://www.facebook.com/BigMilkPL/",
    "https://www.facebook.com/CarrefourPolska",
    "https://www.facebook.com/BiedronkaCodziennie",
    "https://www.facebook.com/zabkapolska",
    "https://www.facebook.com/orlenstopcafe",
    "https://www.facebook.com/ORLENOfficial/",
    "https://www.facebook.com/bp.polska/",
    "https://www.facebook.com/PizzaDominiumPL",
    "https://www.facebook.com/restauracjaThaiWok",
    "https://www.facebook.com/pizzahutpolska",
    "https://www.facebook.com/auchan.retail.polska",
    "https://www.facebook.com/lidlpolska",
    "https://www.facebook.com/Bakoma.online",
    "https://www.facebook.com/PiatnicaOSM/",
    "https://www.facebook.com/MagnumPolska/",
    "https://www.facebook.com/benandjerryspl",
    "https://www.facebook.com/MilkaPoland/",
    "https://www.facebook.com/virtuozismaku/",
    "https://www.facebook.com/PizzaGuseppe",
    "https://www.facebook.com/NestlePL",
    "https://www.facebook.com/DrOetkerPolska",
    "https://www.facebook.com/frosta.polska",
    "https://www.facebook.com/sokolowfanpage",
    "https://www.facebook.com/Zielona.Budka.1947",
    "https://www.facebook.com/NorthFishPL",
    "https://www.facebook.com/KebabKingKrolKebabow",
    "https://www.facebook.com/Nicecreampl",
    "https://www.facebook.com/KinderPoland",
    "https://www.facebook.com/HariboPolska",
    "https://www.facebook.com/LindtPolska",
    "https://www.facebook.com/GalbaniPolska"
  ],
  words: [
    "wegański", "wegańska", "wegańskie", "weganie", "wegan", "weganizm", "wegańskich", "roślinny", "roślinna", "roślinne", "roślinnych", 
    "Wegański", "Wegańska", "Wegańskie", "Weganie", "Wegan", "Weganizm", "Wegańskich", "Roślinny", "Roślinna", "Roślinne", "Roślinnych", 
    "WEGAŃSKI", "WEGAŃSKA", "WEGAŃSKIE", "WEGANIE", "WEGAN", "WEGANIZM", "WEGAŃSKICH", "ROŚLINNY", "ROŚLINNA", "ROŚLINNE", "ROŚLINNYCH"
  ]
}